name: Crystal CI

on:
  push:
    branches: [ "AI2001_Category-Source_Code-SC-Crystal_Main-dev" ]
  pull_request:
    branches: [ "AI2001_Category-Source_Code-SC-Crystal_Main-dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
